<style>
    .left-inner-addon {
        position: relative;
    }
    .left-inner-addon input {
        padding-left: 30px;
    }
    .left-inner-addon i {
        position: absolute;
        padding: 10px 12px;
        pointer-events: none;
    }
</style>
<?php
$title = $this->translate('Edit User');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array('controller' => 'Users', 'action' => 'add')));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<table class="table table-bordered table-striped" style="width:80%;">
    <tr>
        <td width="40%"><?php echo $this->formLabel($form->get('name')); ?></td>
        <td width="60%"><div class="left-inner-addon ">
                <i class="glyphicon glyphicon-user"></i><?php echo $this->formElement($form->get('name')); ?></div></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('email')); ?></td>
        <td><div class="left-inner-addon ">
                <i class="glyphicon glyphicon-envelope"></i><?php echo $this->formElement($form->get('email')); ?></div></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('mobile')); ?></td>
        <td><div class="left-inner-addon ">
                <i class="glyphicon glyphicon-phone"></i><?php echo $this->formElement($form->get('mobile')); ?></div></td>
    </tr>
    <tr>
        <td><?php echo $this->formLabel($form->get('address')); ?></td>
        <td><?php echo $this->formElement($form->get('address')); ?></td>
    </tr>
    <tr>
        <td colspan="2">
          <?php echo $this->formElement($form->get('submit')); ?>
          <br><br>
          <a class="btn btn-danger" href="<?php echo $this->url('users');?>"><span class="glyphicon glyphicon-hand-left"></span>&nbsp; <?php echo $this->translate('Go Back'); ?></a>
        </td>
    </tr>

</table>
<?php echo $this->form()->closeTag();
?>

